### ISSUE TITLE
video not rendered within field type markdown

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-youtube#12] opened 2016-07-29 12:18 UTC
hi,

when using `[plugin:youtube](https://www.youtube.com/watch?v=BK8guP9ov2U)` in markdown field with `validate` set to textarea, video are not rendered
For info i render my field content with `{{ tab.description|markdown }}`, and it works of course in the page `content`
Thanks for any tips

**Comment by redrohX** [comment] 2017-04-07 10:28
Yes I have the same issue. The video only embeds in `{{ content }}`, every other custom markdown field renders the video as an anchor element, where `plugin:youtube` is the anchor text. This should not happen in my opinion, I expect the video to embed for every markdown field.

**Comment by flaviocopes** [comment] 2017-04-07 17:46
The plugin currently only processes the page content, not the page header. Marking as enhancement.

**Comment by rhukster** [comment] 2017-09-28 17:49
The `|markdown` filter runs the string through the Grav standard markdown parser.  However This is not actually markdown and is a custom text filtering function that is done when the content is processed like @flaviocopes mentioned.  Really the only way for it to work as markdown is to create a new plugin (or extend this one) that actually makes a new markdown tag available.  That is not something that is going to happen any time soon.  This plugin was intended as a simple way to add youtube videos to content.  It performs that job adequately.  Feel free to create a PR or create a new plugin that works as a markdown extension.

**Closed by rhukster** 2017-09-28 17:49 UTC
Labels: enhancement
